# Site settings
title: Vol Homes
author: Vol Homes
email: volhomes1@gmail.com
description: Vol Homes - Sell Your House, FAST
url: 'http://volhomes.com'
phone: '865-321-8999'
icon: /assets/images/VolHomes.svg
analytics: UA-45371817-2
mapkey: 'AIzaSyCtcGwRHbo0vJVV0YvFmutoH009c0BAeVY'

# Build settings
markdown: kramdown
permalink: /blog/:title/
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
collections:
  properties:
    output: true
    permalink: /properties-for-sale/:title/
gems:
  - jekyll-sitemap
defaults:
  - scope:
      type: properties
    values:
      layout: property
  - scope:
      type: posts
    values:
      layout: post
