# Site settings
title: Vol Homes
author: Vol Homes
email: volhomes1@gmail.com
description: Vol Homes - Sell Your House, FAST
url: 'http://volhomes.com'
uploads_url: 'http://volhomes.com/uploads/'
images_url: 'http://volhomes.com/assets/images/main/'
phone: '865-321-8999'
icon: /assets/images/VolHomes.svg
fb_admin_id: 652170078151120
fb_app_id: 1711630852476536
analytics: UA-45371817-2
mapkey: 'AIzaSyBHPfAfzDmO8Qw-o3Rtz0u833SPIbIvCB0'
# mapkey: 'AIzaSyCtcGwRHbo0vJVV0YvFmutoH009c0BAeVY'

# Build settings
markdown: kramdown
permalink: /blog/:title/
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
collections:
  properties:
    output: true
    permalink: /properties-for-sale/:title/
gems:
  - jekyll-sitemap
defaults:
  - scope:
      type: properties
    values:
      layout: property
  - scope:
      type: posts
    values:
      layout: post
