# Site settings
title: Title
author: Name # if there is only one author on this site, otherwise delete line
email: email@domain.com
description: Description
url: "http://yourdomain.com"
icon: /assets/images/icon.png
twitter: replace
facebook: replace
google_analytics: replace
disqus: replace


# Build settings
markdown: kramdown
permalink: /posts/:title/
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
gems:
  - jemoji
  - jekyll-sitemap
