# Site settings
title: Vol Homes - Sell Your Home FAST
author: Vol Homes
email: volhomes1@gmail.com
description: Vol Homes - sell your home FAST
url: 'http://test.volhomes.com'
icon: /assets/images/icon.png
social_name: replace
google_analytics: replace
disqus: replace
credits: Seemingly Creative


# Build settings
markdown: kramdown
permalink: /posts/:title/
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
collections:
  properties:
    output: true
    permalink: /properties-for-sale/:path/
    defaults:
      values:
        layout: property
gems:
  - jemoji
  - jekyll-sitemap
