# Site settings
title: Vol Homes - Sell Your Home FAST
author: Vol Homes
email: volhomes1@gmail.com
description: Vol Homes - sell your home FAST
url: 'http://test.volhomes.com'
phone: '865-321-8999'
icon: /assets/images/icon.png
analytics: replace
mapkey: 'AIzaSyCtcGwRHbo0vJVV0YvFmutoH009c0BAeVY'

# Build settings
markdown: kramdown
permalink: /blog/:title/
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
collections:
  properties:
    output: true
    permalink: /properties-for-sale/:path/
gems:
  - jemoji
  - jekyll-sitemap
defaults:
  - scope:
      type: properties
    values:
      layout: property
